#include "token.h"

const char* printTokenType(TokenType type) {
    switch (type) {
        case TOKEN_FN_KW:
            return "TOKEN_FN_KW";
        case TOKEN_IDENTIFIER:
            return "TOKEN_IDENTIFIER";
        case TOKEN_INT:
            return "TOKEN_INT";
        case TOKEN_REAL:
            return "TOKEN_REAL";
        case TOKEN_STRING:
            return "TOKEN_STRING";
        case TOKEN_TRUE_KW:
            return "TOKEN_TRUE_KW";
        case TOKEN_FALSE_KW:
            return "TOKEN_FALSE_KW";
        case TOKEN_NULL_KW:
            return "TOKEN_NULL_KW";
        case TOKEN_COND_KW:
            return "TOKEN_COND_KW";
        case TOKEN_SWITCH_KW:
            return "TOKEN_SWITCH_KW";
        case TOKEN_LET_KW:
            return "TOKEN_LET_KW";
        case TOKEN_IMPORT_KW:
            return "TOKEN_IMPORT_KW";
        case TOKEN_AS_KW:
            return "TOKEN_AS_KW";
        case TOKEN_BREAKPOINT_KW:
            return "TOKEN_BREAKPOINT_KW";
        case TOKEN_TRY_KW:
            return "TOKEN_TRY_KW";
        case TOKEN_AND_KW:
            return "TOKEN_AND_KW";
        case TOKEN_OR_KW:
            return "TOKEN_OR_KW";
        case TOKEN_NOT_OP:
            return "TOKEN_NOT_OP";
        case TOKEN_NOT_KW:
            return "TOKEN_NOT_KW";
        case TOKEN_GREATER_OP:
            return "TOKEN_GREATER_OP";
        case TOKEN_GREATER_KW:
            return "TOKEN_GREATER_KW";
        case TOKEN_GREATER_EQUAL_OP:
            return "TOKEN_GREATER_EQUAL_OP";
        case TOKEN_GREATER_EQUAL_KW:
            return "TOKEN_GREATER_EQUAL_KW";
        case TOKEN_LESS_OP:
            return "TOKEN_LESS_OP";
        case TOKEN_LESS_KW:
            return "TOKEN_LESS_KW";
        case TOKEN_LESS_EQUAL_OP:
            return "TOKEN_LESS_EQUAL_OP";
        case TOKEN_LESS_EQUAL_KW:
            return "TOKEN_LESS_EQUAL_KW";
        case TOKEN_BAND_OP:
            return "TOKEN_BAND_OP";
        case TOKEN_BAND_KW:
            return "TOKEN_BAND_KW";
        case TOKEN_BOR_OP:
            return "TOKEN_BOR_OP";
        case TOKEN_BOR_KW:
            return "TOKEN_BOR_KW";
        case TOKEN_BXOR_OP:
            return "TOKEN_BXOR_OP";
        case TOKEN_BXOR_KW:
            return "TOKEN_BXOR_KW";
        case TOKEN_BNOT_OP:
            return "TOKEN_BNOT_OP";
        case TOKEN_BNOT_KW:
            return "TOKEN_BNOT_KW";
        case TOKEN_LSHIFT_OP:
            return "TOKEN_LSHIFT_OP";
        case TOKEN_LSHIFT_KW:
            return "TOKEN_LSHIFT_KW";
        case TOKEN_RSHIFT_OP:
            return "TOKEN_RSHIFT_OP";
        case TOKEN_RSHIFT_KW:
            return "TOKEN_RSHIFT_KW";
        case TOKEN_STAR_OP:
            return "TOKEN_STAR_OP";
        case TOKEN_STAR_KW:
            return "TOKEN_STAR_KW";
        case TOKEN_SLASH_OP:
            return "TOKEN_SLASH_OP";
        case TOKEN_SLASH_KW:
            return "TOKEN_SLASH_KW";
        case TOKEN_PLUS_OP:
            return "TOKEN_PLUS_OP";
        case TOKEN_PLUS_KW:
            return "TOKEN_PLUS_KW";
        case TOKEN_MINUS_OP:
            return "TOKEN_MINUS_OP";
        case TOKEN_MINUS_KW:
            return "TOKEN_MINUS_KW";
        case TOKEN_MODULO_OP:
            return "TOKEN_MODULO_OP";
        case TOKEN_MODULO_KW:
            return "TOKEN_MODULO_KW";
        case TOKEN_EQUAL_OP:
            return "TOKEN_EQUAL_OP";
        case TOKEN_EQUAL_KW:
            return "TOKEN_EQUAL_KW";
        case TOKEN_NOT_EQUAL_OP:
            return "TOKEN_NOT_EQUAL_OP";
        case TOKEN_NOT_EQUAL_KW:
            return "TOKEN_NOT_EQUAL_KW";
        case TOKEN_LPAREN:
            return "TOKEN_LPAREN";
        case TOKEN_RPAREN:
            return "TOKEN_RPAREN";
        case TOKEN_LBRAKET:
            return "TOKEN_LBRAKET";
        case TOKEN_RBRAKET:
            return "TOKEN_RBRAKET";
        case TOKEN_ERROR:
            return "TOKEN_ERROR";
        case TOKEN_EOF:
            return "TOKEN_EOF";
        case TOKEN_ARROW_KW:
            return "TOKEN_ARROW_KW";
        default:
            return "UNKNOWN_TOKEN";
    }
}
